### ISSUE TITLE
Feature: Open Harmony Support

### ISSUE THREAD

**Issue by Chilledheart** [Chilledheart/yass#698]
- [x] add yass_core support
- [x] open harmony log support
- [x] add packaging support and basic ui support (#712)
- [x] add ui support (typejs #715 #716)
- [x] add protect fd support (client & typejs)
- [ ] add vpn support code (depends on sdk api level 10)
- [x] worker support (#710 #711 #713 #714)
- [x] rust platform and std support (#707 https://doc.rust-lang.org/rustc/platform-support.html)
- [x] rust supplement library (https://github.com/nix-rust/nix/pull/2301 https://github.com/rust-lang/socket2/pull/491)
- [x] rust logger support (#708)
- [x] tun2proxy support (#708 #709)
- [x] code clean up (#717)

reference: https://gitee.com/openharmony/docs/blob/master/zh-cn/application-dev/connectivity/net-vpn.md#/openharmony/docs/blob/master/zh-cn/application-dev/reference/apis/js-apis-net-vpn.md
and https://gitee.com/openharmony/docs/blob/master/zh-cn/application-dev/connectivity/net-vpn.md 

napi reference: https://nodejs.org/dist/latest-v11.x/docs/api/n-api.html#n_api_napi_call_function

**Comment by Chilledheart** [comment]
and [ ] github action ci support
